version: '3.7'
services:
  php:
    build: ./php
    volumes:
      - ./server:/var/www/
    ports:
      - "8080:80"
    depends_on:
      - mysql
    container_name: php

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./server:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    tty: true
    build: ./db
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      TZ: "Asia/Tokyo"
    container_name: mysql
