version: '3.7'
services:
  php:
    build: ./php
    volumes:
      - ./app:/var/www/
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
    container_name: php

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql-db:
    tty: true
    build: ./db
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: cue-simulator
      TZ: "Asia/Tokyo"
    container_name: mysql-db
